// <auto-generated />
using InventorySystemAPI.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InventorySystemAPI.Migrations
{
    [DbContext(typeof(StockContext))]
    [Migration("20190214051202_Added Company Table")]
    partial class AddedCompanyTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InventorySystemAPI.Models.Company", b =>
                {
                    b.Property<int>("company_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("company_name")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("country")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("currency")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("message")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("phone")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("service_charge_valie")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("vat_charge_value")
                        .HasColumnType("varchar(100)");

                    b.HasKey("company_id");

                    b.ToTable("Companies");
                });
#pragma warning restore 612, 618
        }
    }
}
