// <auto-generated />
using InventorySystemAPI.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InventorySystemAPI.Migrations
{
    [DbContext(typeof(StockContext))]
    partial class StockContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InventorySystemAPI.Models.Attribute_value", b =>
                {
                    b.Property<int>("attribute_value_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("atrribute_id");

                    b.Property<string>("attribute_value_desc")
                        .HasColumnType("varchar(255)");

                    b.HasKey("attribute_value_id");

                    b.ToTable("Attribute_values");
                });

            modelBuilder.Entity("InventorySystemAPI.Models.Attributes", b =>
                {
                    b.Property<int>("attribute_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("attribute_name")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("attribute_status");

                    b.HasKey("attribute_id");

                    b.ToTable("Attributes");
                });

            modelBuilder.Entity("InventorySystemAPI.Models.Brands", b =>
                {
                    b.Property<int>("brand_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("brand_name")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("brand_status");

                    b.HasKey("brand_id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("InventorySystemAPI.Models.Categories", b =>
                {
                    b.Property<int>("category_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("category_name")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("category_status");

                    b.HasKey("category_id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("InventorySystemAPI.Models.Company", b =>
                {
                    b.Property<int>("company_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("company_name")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("country")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("currency")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("message")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("phone")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("service_charge_valie")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("vat_charge_value")
                        .HasColumnType("varchar(100)");

                    b.HasKey("company_id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("InventorySystemAPI.Models.Products", b =>
                {
                    b.Property<int>("product_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("attribute_value_id")
                        .HasColumnType("text");

                    b.Property<int>("availability");

                    b.Property<string>("brand_id")
                        .HasColumnType("text");

                    b.Property<string>("category_id")
                        .HasColumnType("text");

                    b.Property<string>("product_description")
                        .HasColumnType("text");

                    b.Property<string>("product_image")
                        .HasColumnType("text");

                    b.Property<string>("product_name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("product_price")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("product_qty")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("product_sku")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("store_id");

                    b.HasKey("product_id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("InventorySystemAPI.Models.Stores", b =>
                {
                    b.Property<int>("store_id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("store_name")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("store_status");

                    b.HasKey("store_id");

                    b.ToTable("Stores");
                });
#pragma warning restore 612, 618
        }
    }
}
